language: cpp
compiler:
    - gcc
install:
    - sudo apt-get update
    - sudo apt-get install libcppunit-dev
    - sudo apt-get install valgrind
    - mkdir bin
    - make
script: 
    - ./tests
    - valgrind --leak-check=yes ./tests

notifications:
    recipients:
        - forster.matth@gmail.com
    email:
        on_success: change
        on_failure: always
